name: Build Docker Image

on:
  workflow_dispatch: # Manueller Trigger
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest-4-cores  # Mehr Speicher und CPU
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Free up space  # Neuer Step für mehr Speicherplatz
      run: |
        echo "Speicher vor Cleanup:"
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /usr/local/lib/android
        sudo apt-get clean
        echo "Speicher nach Cleanup:"
        df -h
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          matmax/opentuneweaver-aio:latest
          matmax/opentuneweaver-aio:${{ github.run_number }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64  # Nur eine Plattform für weniger Speicherverbrauch
